<table class="table table-bordered table-striped">
  <thead>
    <th>Brands</th>
    <th>Agency</th>
    <th>Magazines</th>
    <th>Productions</th>
    <th>Others</th>
  </thead>
  <tbody>
    <td>
    <ul>
      <li>first</li>
    </ul>
    <tr><td>second</td></tr>
    <tr><td>third</td></tr>
  </td>
    <td>
    <ul>
      <li>first</li>
    </ul>
  </td>
  </tbody>
</table>